# Generated by Django 6.0.3 on 2026-05-05 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('diyprojects', '0003_favorite_projectrating_projectreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreview',
            name='review_Image',
            field=models.ImageField(null=True, upload_to='images/diyprojects/'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_projects', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='diyprojects.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='projectrating',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_projects', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_projects', to='accounts.profile'),
        ),
    ]
