# Generated by Django 6.0.3 on 2026-05-05 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0004_projectreview_review_image_alter_favorite_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrating',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rater', to='diyprojects.project'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='diyprojects.project'),
        ),
    ]
