# Generated by Django 6.0.3 on 2026-05-06 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0005_alter_projectrating_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='diyprojects.project'),
        ),
    ]
