# Generated by Django 6.0.3 on 2026-05-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0006_alter_favorite_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrating',
            old_name='profile',
            new_name='rater',
        ),
    ]
