# Generated by Django 6.0.3 on 2026-05-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='application',
            new_name='applicant',
        ),
    ]
