# Generated by Django 6.0.3 on 2026-03-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commision',
            new_name='Commission',
        ),
    ]
