# Generated by Django 6.0.3 on 2026-05-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_rename_application_jobapplication_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
